[package]
name = "haskell-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3"
borsh = "0.9"
haskell-ffi-derive = { path = "../haskell-ffi-derive" }
ref-cast = "1.0"
serde = "1.0"
